/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

public class Solution {
    public char FindTheDifference(string s, string t) {
         int[] counts = new int[26]; 

    
        foreach (char ch in t) {
            counts[ch - 'a']++;
        }
        
        foreach (char ch in s) {
            counts[ch - 'a']--;
        }
        
        for (int i = 0; i < 26; i++) {
            if (counts[i] > 0) {
                return (char)('a' + i);
            }
        }
        
        return ' '; 
    }
}